CITY_AREA_MAP = {
    "Baringo": ["Baringo central", "Baringo north", "Baringo south", "Eldama ravine", "Mogotio", "Tiaty"],
    "Bomet": ["Bomet central", "Bomet east", "Chepalungu", "Konoin", "Sotik"],
    "Bungoma": ["Bumula", "Kabuchai", "Kanduyi", "Kimilili", "Mt Elgon", "Sirisia", "Tongaren", "Webuye east", "Webuye west"],
    "Busia": ["Budalangi", "Butula", "Funyula", "Nambale", "Teso North", "Teso South"],
    "Elgeyo-Marakwet": ["Keiyo north", "Keiyo south", "Marakwet east", "Marakwet west"],
    "Embu": ["Manyatta", "Mbeere north", "Mbeere south", "Runyenjes"],
    "Garissa": ["Daadab", "Fafi", "Garissa", "Hulugho", "Ijara", "Lagdera balambala"],
    "Homa Bay": ["Homabay town", "Kabondo", "Karachwonyo", "Kasipul", "Mbita", "Ndhiwa", "Rangwe", "Suba"],
    "Isiolo": ["Central", "Garba tula", "Kina", "Merit", "Oldonyiro", "Sericho"],
    "Kajiado": ["Isinya", "Kajiado Central", "Kajiado North", "Loitokitok", "Mashuuru"],
    "Kakamega": ["Butere", "Kakamega central", "Kakamega east", "Kakamega north", "Kakamega south", "Khwisero", "Lugari", "Lukuyani", "Lurambi", "Matete", "Mumias", "Mutungu", "Navakholo"],
    "Kericho": ["Ainamoi", "Belgut", "Bureti", "Kipkelion east", "Kipkelion west", "Soin sigowet"],
    "Kiambu": ["Gatundu north", "Gatundu south", "Githunguri", "Juja", "Kabete", "Kiambaa", "Kiambu", "Kikuyu", "Limuru", "Ruiru", "Thika town", "Lari"],
    "Kilifi": ["Ganze", "Kaloleni", "Kilifi north", "Kilifi south", "Magarini", "Malindi", "Rabai"],
    "Kirinyaga": ["Kirinyaga central", "Kirinyaga east", "Kirinyaga west", "Mwea east", "Mwea west"],
    "Kisii": [],
    "Kisumu": ["Kisumu central", "Kisumu east", "Kisumu west", "Mohoroni", "Nyakach", "Nyando", "Seme"],
    "Kitui": ["Ikutha", "Katulani", "Kisasi", "Kitui central", "Kitui west", "Lower yatta", "Matiyani", "Migwani", "Mutitu", "Mutomo", "Muumonikyusu", "Mwingi central", "Mwingi east", "Nzambani", "Tseikuru"],
    "Kwale": ["Kinango", "Lungalunga", "Msambweni", "Matuga"],
    "Laikipia": ["Laikipia central", "Laikipia east", "Laikipia north", "Laikipia west", "Nyahururu"],
    "Lamu": ["Lamu East", "Lamu West"],
    "Machakos": ["Kathiani", "Machakos town", "Masinga", "Matungulu", "Mavoko", "Mwala", "Yatta"],
    "Makueni": ["Kaiti", "Kibwezi west", "Kibwezi east", "Kilome", "Makueni", "Mbooni"],
    "Mandera": ["Banissa", "Lafey", "Mandera East", "Mandera North", "Mandera South", "Mandera West"],
    "Marsabit": ["Laisamis", "Moyale", "North hor", "Saku"],
    "Meru": ["Buuri", "Igembe central", "Igembe north", "Igembe south", "Imenti central", "Imenti north", "Imenti south", "Tigania east", "Tigania west"],
    "Migori": ["Awendo", "Kuria east", "Kuria west", "Mabera", "Ntimaru", "Rongo", "Suna east", "Suna west", "Uriri"],
    "Mombasa": ["Changamwe", "Jomvu", "Kisauni", "Likoni", "Mvita", "Nyali"],
    "Murang'a": ["Gatanga", "Kahuro", "Kandara", "Kangema", "Kigumo", "Kiharu", "Mathioya", "Murang'a south"],
    "Nairobi": ["Dagoretti North Sub County", "Dagoretti South Sub County", "Embakasi Central Sub County", "Embakasi East Sub County", "Embakasi North Sub County", "Embakasi South Sub County", "Embakasi West Sub County", "Kamukunji Sub County", "Kasarani Sub County", "Kibra Sub County", "Lang'ata Sub County", "Makadara Sub County", "Mathare Sub County", "Roysambu Sub County", "Ruaraka Sub County", "Starehe Sub County", "Westlands Sub County"],
    "Nakuru": ["Bahati", "Gilgil", "Kuresoi north", "Kuresoi south", "Molo", "Naivasha", "Nakuru town east", "Nakuru town west", "Njoro", "Rongai", "Subukia"],
    "Nandi": ["Aldai", "Chesumei", "Emgwen", "Mosop", "Nandi hills", "Tindiret"],
    "Narok": ["Narok east", "Narok north", "Narok south", "Narok west", "Transmara east", "Transmara west"],
    "Nyamira": ["Borabu", "Manga", "Masaba north", "Nyamira north", "Nyamira south"],
    "Nyandarua": ["Kinangop", "Kipipiri", "Ndaragwa", "Ol Kalou", "Ol joro orok"],
    "Nyeri": ["Kieni east", "Kieni west", "Mathira east", "Mathira west", "Mkurweni", "Nyeri town", "Othaya", "Tetu"],
    "Samburu": ["Samburu east", "Samburu north", "Samburu west"],
    "Siaya": ["Alego usonga", "Bondo", "Gem", "Rarieda", "Ugenya", "Ugunja"],
    "Taita-Taveta": ["Mwatate", "Taveta", "Voi", "Wundanyi"],
    "Tana River": ["Bura", "Galole", "Garsen"],
    "Tharaka-Nithi": ["Chuka", "Igambang'ombe", "Maara", "Muthambi", "Tharaka north", "Tharaka south"],
    "Trans-Nzoia": ["Cherangany", "Endebess", "Kiminini", "Kwanza", "Saboti"],
    "Turkana": ["Loima", "Turkana central", "Turkana east", "Turkana north", "Turkana south"],
    "Uasin Gishu": ["Ainabkoi", "Kapseret", "Kesses", "Moiben", "Soy", "Turbo"],
    "Vihiga": ["Emuhaya", "Hamisi", "Luanda", "Sabatia", "Vihiga"],
    "Wajir": ["Eldas", "Tarbaj", "Wajir East", "Wajir North", "Wajir South", "Wajir West"],
    "West Pokot": ["Central Pokot", "North Pokot", "Pokot South", "West Pokot"],
}


def is_valid_city_area(city: str | None, area: str | None) -> bool:
    if not city and not area:
        return True
    if not city or not area:
        return False
    return area in CITY_AREA_MAP.get(city, [])
